# Generated by Django 2.2.7 on 2020-01-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dr_register',
            name='field',
            field=models.CharField(default='Neurologist', max_length=20),
        ),
        migrations.AddField(
            model_name='dr_register',
            name='qualfication',
            field=models.CharField(default='IOM', max_length=50),
        ),
    ]
